// packages/react/src/elements/components/ripple-effect/ripple-effect.jsx
import * as React from "react";
import "./button.css";
import { rippleEffectService } from "./ripple-effect.service";

function IonRippleEffect(props) {
  function classes() {
    return rippleEffectService.getClasses(
      props.mode,
      props.type,
      props.className
    );
  }

  return <div role="presentation" className={classes().base} />;
}

export default IonRippleEffect;

// packages/svelte/src/elements/components/ripple-effect/ripple-effect.svelte
<script>
  import "./button.css";
  import { rippleEffectService } from "./ripple-effect.service";

  export let mode;
  export let type;
  export let className;

  $: classes = () => {
    return rippleEffectService.getClasses(mode, type, className);
  };
</script>

<div role="presentation" class={classes().base} />
